/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO009FUNC
#define ROOCFAUTO009FUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto009Func : public RooAbsReal {
public:
  RooCFAuto009Func() {} ; 
  RooCFAuto009Func(const char *name, const char *title,
	      RooAbsReal& _res_a,
	      RooAbsReal& _peak,
	      RooAbsReal& _res_b,
	      RooAbsReal& _res_c);
  RooCFAuto009Func(const RooCFAuto009Func& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto009Func(*this,newname); }
  inline virtual ~RooCFAuto009Func() { }

protected:

  RooRealProxy res_a ;
  RooRealProxy peak ;
  RooRealProxy res_b ;
  RooRealProxy res_c ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto009Func,1) // Your description goes here...
};
 
#endif
