/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooCFAuto003Pdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto003Pdf) 

 RooCFAuto003Pdf::RooCFAuto003Pdf(const char *name, const char *title, 
                        RooAbsReal& _a,
                        RooAbsReal& _mass,
                        RooAbsReal& _b,
                        RooAbsReal& _c,
                        RooAbsReal& _d) :
   RooAbsPdf(name,title), 
   a("a","a",this,_a),
   mass("mass","mass",this,_mass),
   b("b","b",this,_b),
   c("c","c",this,_c),
   d("d","d",this,_d)
 { 
 } 


 RooCFAuto003Pdf::RooCFAuto003Pdf(const RooCFAuto003Pdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   a("a",this,other.a),
   mass("mass",this,other.mass),
   b("b",this,other.b),
   c("c",this,other.c),
   d("d",this,other.d)
 { 
 } 



 Double_t RooCFAuto003Pdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return (pow(a*(1-mass/8000),b))/pow(mass/8000,c+d*log(mass/8000)) ; 
 } 



