/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO006FUNC
#define ROOCFAUTO006FUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto006Func : public RooAbsReal {
public:
  RooCFAuto006Func() {} ; 
  RooCFAuto006Func(const char *name, const char *title,
	      RooAbsReal& _nbkg_kappa_b,
	      RooAbsReal& _nbkg_kappa_m,
	      RooAbsReal& _mass,
	      RooAbsReal& _nbkg_kappa_msquared,
	      RooAbsReal& _beta_nbkg);
  RooCFAuto006Func(const RooCFAuto006Func& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto006Func(*this,newname); }
  inline virtual ~RooCFAuto006Func() { }

protected:

  RooRealProxy nbkg_kappa_b ;
  RooRealProxy nbkg_kappa_m ;
  RooRealProxy mass ;
  RooRealProxy nbkg_kappa_msquared ;
  RooRealProxy beta_nbkg ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto006Func,1) // Your description goes here...
};
 
#endif
