/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

// class declaration include file below retrieved from workspace code storage
#include "RooCFAuto008Func.h"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto008Func) 

 RooCFAuto008Func::RooCFAuto008Func(const char *name, const char *title, 
                        RooAbsReal& _mass_kappa,
                        RooAbsReal& _beta_mass) :
   RooAbsReal(name,title), 
   mass_kappa("mass_kappa","mass_kappa",this,_mass_kappa),
   beta_mass("beta_mass","beta_mass",this,_beta_mass)
 { 
 } 


 RooCFAuto008Func::RooCFAuto008Func(const RooCFAuto008Func& other, const char* name) :  
   RooAbsReal(other,name), 
   mass_kappa("mass_kappa",this,other.mass_kappa),
   beta_mass("beta_mass",this,other.beta_mass)
 { 
 } 



 Double_t RooCFAuto008Func::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return pow(mass_kappa,beta_mass) ; 
 } 



