/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

// class declaration include file below retrieved from workspace code storage
#include "RooCFAuto001Func.h"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto001Func) 

 RooCFAuto001Func::RooCFAuto001Func(const char *name, const char *title, 
                        RooAbsReal& _peak,
                        RooAbsReal& _eff_a,
                        RooAbsReal& _eff_b,
                        RooAbsReal& _eff_c) :
   RooAbsReal(name,title), 
   peak("peak","peak",this,_peak),
   eff_a("eff_a","eff_a",this,_eff_a),
   eff_b("eff_b","eff_b",this,_eff_b),
   eff_c("eff_c","eff_c",this,_eff_c)
 { 
 } 


 RooCFAuto001Func::RooCFAuto001Func(const RooCFAuto001Func& other, const char* name) :  
   RooAbsReal(other,name), 
   peak("peak",this,other.peak),
   eff_a("eff_a",this,other.eff_a),
   eff_b("eff_b",this,other.eff_b),
   eff_c("eff_c",this,other.eff_c)
 { 
 } 



 Double_t RooCFAuto001Func::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 0.5*eff_c*(1+TMath::Erf((peak-eff_a)/(eff_b*sqrt(2)))) ; 
 } 



