/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO008FUNC
#define ROOCFAUTO008FUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto008Func : public RooAbsReal {
public:
  RooCFAuto008Func() {} ; 
  RooCFAuto008Func(const char *name, const char *title,
	      RooAbsReal& _res_a,
	      RooAbsReal& _peak,
	      RooAbsReal& _res_b,
	      RooAbsReal& _res_c);
  RooCFAuto008Func(const RooCFAuto008Func& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto008Func(*this,newname); }
  inline virtual ~RooCFAuto008Func() { }

protected:

  RooRealProxy res_a ;
  RooRealProxy peak ;
  RooRealProxy res_b ;
  RooRealProxy res_c ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto008Func,1) // Your description goes here...
};
 
#endif
