/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO010FUNC
#define ROOCFAUTO010FUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto010Func : public RooAbsReal {
public:
  RooCFAuto010Func() {} ; 
  RooCFAuto010Func(const char *name, const char *title,
	      RooAbsReal& _res_a,
	      RooAbsReal& _peak,
	      RooAbsReal& _res_b,
	      RooAbsReal& _res_c);
  RooCFAuto010Func(const RooCFAuto010Func& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto010Func(*this,newname); }
  inline virtual ~RooCFAuto010Func() { }

protected:

  RooRealProxy res_a ;
  RooRealProxy peak ;
  RooRealProxy res_b ;
  RooRealProxy res_c ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto010Func,1) // Your description goes here...
};
 
#endif
