/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO002PDF
#define ROOCFAUTO002PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto002Pdf : public RooAbsPdf {
public:
  RooCFAuto002Pdf() {} ; 
  RooCFAuto002Pdf(const char *name, const char *title,
	      RooAbsReal& _a,
	      RooAbsReal& _mass,
	      RooAbsReal& _b,
	      RooAbsReal& _c,
	      RooAbsReal& _d);
  RooCFAuto002Pdf(const RooCFAuto002Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto002Pdf(*this,newname); }
  inline virtual ~RooCFAuto002Pdf() { }

protected:

  RooRealProxy a ;
  RooRealProxy mass ;
  RooRealProxy b ;
  RooRealProxy c ;
  RooRealProxy d ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto002Pdf,1) // Your description goes here...
};
 
#endif
