/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO003PDF
#define ROOCFAUTO003PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto003Pdf : public RooAbsPdf {
public:
  RooCFAuto003Pdf() {} ; 
  RooCFAuto003Pdf(const char *name, const char *title,
	      RooAbsReal& _a,
	      RooAbsReal& _mass,
	      RooAbsReal& _b,
	      RooAbsReal& _c,
	      RooAbsReal& _d);
  RooCFAuto003Pdf(const RooCFAuto003Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto003Pdf(*this,newname); }
  inline virtual ~RooCFAuto003Pdf() { }

protected:

  RooRealProxy a ;
  RooRealProxy mass ;
  RooRealProxy b ;
  RooRealProxy c ;
  RooRealProxy d ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto003Pdf,1) // Your description goes here...
};
 
#endif
